### ISSUE TITLE
アカウント作成時のパフォーマンスについて

### ISSUE THREAD

**Issue by monkukui** [sono8stream/atcoder-anytime#1]
## WHAT
アカウント作成時のパフォーマンスを `0` にする

## WHY
Codeforces Anytime では、アカウント作成時のパフォーマンスは `0` となっていましたが、AtCoder Anytime では、パフォーマンスがレートと一致しています。

Codeforces Anytime に合わせるのが妥当だと思いました。

![スクリーンショット 2021-03-29 16 09 03](https://user-images.githubusercontent.com/47474057/112799377-38b21600-90a9-11eb-8dcc-6b2c0e05e690.png)
![スクリーンショット 2021-03-29 16 08 12](https://user-images.githubusercontent.com/47474057/112799381-3a7bd980-90a9-11eb-9d7a-dd4943c5711a.png)

**Comment by sono8stream** [comment]
報告いただきありがとうございます．

登録時のパフォーマンスがゼロでないのは仕様です．
AtCoderの方はCodeforcesと異なり，過去のパフォーマンスをもとに新たなレートを計算します．このため，レートを引き継いだアカウントでは登録時のパフォーマンスがゼロになっていると，実質的にレートを引き継いだことになりません．

Codeforces Anytimeの方と仕様がバラバラで混乱を招くようので，Codeforces Anytimeの方で登録時のパフォーマンスがレートと一致するように修正します．

**Comment by monkukui** [comment]
なるほど、ご回答ありがとうございます。
納得しました。
